services:
  guacamole:
    image: jwetzell/guacamole:1.5.5
    container_name: guacamole
    volumes:
      -  ./postgres:/config
    ports:
      - 8080:8080
    environment:
      - EXTENSIONS=auth-totp
volumes:
  postgres:
    driver: local
